#!/usr/bin/env python3
# ============================================================
#  _skill_meta.py
#  共享模块：Skill 元数据映射表（单一真相源）
#  被 rebuild-skill-metas.py 和 apply-skill-categories.py 共用
#
#  slug → (category, domain, tags)
# ============================================================

SKILL_META = {
    "git-xywh": ("shared.workflow", "shared", ["git", "workflow", "commit"]),
    # code 域
    "architecture-patterns": ("code.architecture", "code", ["architecture", "backend", "DDD", "clean"]),
    "code-review": ("code.review", "code", ["review", "quality"]),
    "refactor-safely": ("code.review", "code", ["refactor", "safe"]),
    "requesting-code-review": ("code.review", "code", ["review", "workflow"]),
    "simplify": ("code.review", "code", ["simplify", "quality"]),
    "verification-before-completion": ("code.testing", "code", ["verify", "completion"]),
    "security-auditor": ("code.security", "code", ["security", "audit"]),
    "dispatching-parallel-agents": ("code.ai-agent", "code", ["parallel", "agent", "dispatch"]),
    "subagent-driven-development": ("code.ai-agent", "code", ["SDD", "agent", "subagent"]),
    "prompt-engineering-expert": ("code.ai-agent", "code", ["prompt", "LLM"]),
    "self-improving": ("code.ai-agent", "code", ["self-improve", "learning"]),
    "superdesign": ("code.frontend", "code", ["design", "UI"]),
    "ui-ux-pro-max": ("code.frontend", "code", ["UI", "UX"]),
    "using-git-worktrees": ("code.tooling", "code", ["git", "worktree"]),

    # novel 域
    "inkos": ("novel.creation", "novel", ["创作", "系统"]),
    "novel-generator": ("novel.creation", "novel", ["爽文", "生成"]),
    "humanizer": ("novel.polish", "novel", ["humanizer", "AI痕迹"]),
    "fanqie": ("novel.publish", "novel", ["番茄", "平台"]),
    "fanqie-novel-auto-publish": ("novel.publish", "novel", ["番茄", "自动发布"]),
    "web-novel-publishing-readiness-and-quality-check-skill": ("novel.publish", "novel", ["发布", "质检"]),

    # shared 域
    "brainstorming": ("shared.planning", "shared", ["头脑风暴", "设计"]),
    "writing-plans": ("shared.planning", "shared", ["plan", "writing"]),
    "executing-plans": ("shared.planning", "shared", ["plan", "execute"]),
    "planning-with-files": ("shared.planning", "shared", ["plan", "files"]),
    "project-planner": ("shared.planning", "shared", ["plan", "project"]),
    "deep-research": ("shared.research", "shared", ["研究", "搜索"]),
    "playwright": ("shared.workflow", "shared", ["browser", "automation"]),
    "find-skills": ("shared.workflow", "shared", ["skill", "discover"]),
    "skill-vetter": ("shared.workflow", "shared", ["skill", "vet", "security"]),
    "auto-updater": ("shared.workflow", "shared", ["update", "cron"]),
    "free-ride": ("shared.workflow", "shared", ["model", "free"]),
    "summarize": ("shared.workflow", "shared", ["summarize"]),
    "excel-xlsx": ("shared.docs", "shared", ["excel", "spreadsheet"]),
    "human-writing": ("shared.docs", "shared", ["writing", "human"]),
    "accessibility": ("code.frontend", "code", ["code", "frontend"]),
    "agent-browser": ("code.testing", "code", ["code", "testing"]),
    "agent-shield": ("shared.workflow", "shared", ["security", "audit"]),
    "agentic-engineering": ("code.ai-agent", "code", ["code", "ai-agent"]),
    "ai-first-engineering": ("code.ai-agent", "code", ["code", "ai-agent"]),
    "ai-regression-testing": ("code.architecture", "code", ["code", "architecture"]),
    "analyze-architecture": ("code.intelligence", "code", ["code", "intelligence"]),
    "analyze-impact": ("code.intelligence", "code", ["code", "intelligence"]),
    "api-connector-builder": ("code.architecture", "code", ["code", "architecture"]),
    "api-design": ("code.architecture", "code", ["code", "architecture"]),
    "architecture-decision-records": ("code.architecture", "code", ["code", "architecture"]),
    "article-writing": ("shared.docs", "shared", ["shared", "docs"]),
    "auto-compact": ("code.optimization", "code", ["code", "optimization"]),
    "automation-audit-ops": ("code.ai-agent", "code", ["code", "ai-agent"]),
    "autonomous-agent-harness": ("code.ai-agent", "code", ["code", "ai-agent"]),
    "backend-doc-generator": ("code.architecture", "code", ["code", "architecture"]),
    "backend-patterns": ("code.architecture", "code", ["code", "architecture"]),
    "benchmark": ("code.testing", "code", ["code", "testing"]),
    "benchmark-methodology": ("code.testing", "code", ["code", "testing"]),
    "benchmark-optimization-loop": ("code.testing", "code", ["code", "testing"]),
    "blueprint": ("code.architecture", "code", ["code", "architecture"]),
    "brand-discovery": ("shared.docs", "shared", ["shared", "docs"]),
    "brand-voice": ("shared.docs", "shared", ["shared", "docs"]),
    "ceo-orchestration": ("shared.workflow", "shared", ["orchestration", "ceo"]),
    "ck": ("code.languages", "code", ["code", "languages"]),
    "code-insight-stack": ("code.intelligence", "code", ["code", "intelligence"]),
    "code-tour": ("code.architecture", "code", ["code", "architecture"]),
    "codebase-onboarding": ("code.architecture", "code", ["code", "architecture"]),
    "coding-standards": ("code.architecture", "code", ["code", "architecture"]),
    "context-budget": ("code.ai-agent", "code", ["code", "ai-agent"]),
    "continuous-agent-loop": ("code.architecture", "code", ["code", "architecture"]),
    "continuous-learning": ("shared.workflow", "shared", ["learning", "continuous"]),
    "cost-aware-llm-pipeline": ("code.architecture", "code", ["code", "architecture"]),
    "cost-tracking": ("code.ai-agent", "code", ["code", "ai-agent"]),
    "cpp-coding-standards": ("shared.docs", "shared", ["shared", "docs"]),
    "cursor-orchestration": ("code.testing", "code", ["code", "testing"]),
    "database-migrations": ("code.languages", "code", ["code", "languages"]),
    "deployment-patterns": ("code.architecture", "code", ["code", "architecture"]),
    "design-system": ("code.architecture", "code", ["code", "architecture"]),
    "docker-patterns": ("code.architecture", "code", ["code", "architecture"]),
    "document-review": ("code.review", "code", ["code", "review"]),
    "documentation-lookup": ("code.languages", "code", ["code", "languages"]),
    "dotnet-patterns": ("code.architecture", "code", ["code", "architecture"]),
    "e2e-testing": ("code.architecture", "code", ["code", "architecture"]),
    "ecc-guide": ("code.ai-agent", "code", ["code", "ai-agent"]),
    "ecc-tools-cost-audit": ("code.ai-agent", "code", ["code", "ai-agent"]),
    "error-handling": ("code.architecture", "code", ["code", "architecture"]),
    "exa-search": ("code.ai-agent", "code", ["code", "ai-agent"]),
    "fact-check": ("news.creation", "news", ["news", "creation"]),
    "fal-ai-media": ("code.ai-agent", "code", ["code", "ai-agent"]),
    "fastapi-patterns": ("code.architecture", "code", ["code", "architecture"]),
    "frontend-a11y": ("code.architecture", "code", ["code", "architecture"]),
    "frontend-design": ("code.review", "code", ["code", "review"]),
    "frontend-design-direction": ("code.testing", "code", ["code", "testing"]),
    "frontend-patterns": ("code.architecture", "code", ["code", "architecture"]),
    "frontend-slides": ("code.languages", "code", ["code", "languages"]),
    "get-callees": ("code.intelligence", "code", ["code", "intelligence"]),
    "get-callers": ("code.intelligence", "code", ["code", "intelligence"]),
    "git-workflow": ("code.architecture", "code", ["code", "architecture"]),
    "golang-patterns": ("code.architecture", "code", ["code", "architecture"]),
    "harness-health": ("shared.workflow", "shared", ["health", "check"]),
    "humanizer-zh": ("novel.polish", "novel", ["novel", "polish"]),
    "index-project": ("code.intelligence", "code", ["code", "intelligence"]),
    "java-coding-standards": ("code.architecture", "code", ["code", "architecture"]),
    "jpa-patterns": ("code.architecture", "code", ["code", "architecture"]),
    "junli-ai-novel": ("novel.creation", "novel", ["novel", "creation"]),
    "karpathy-guidelines": ("code.baseline", "code", ["code", "baseline"]),
    "kubernetes-patterns": ("code.architecture", "code", ["code", "architecture"]),
    "lsp-query": ("code.lsp", "code", ["code", "lsp"]),
    "memory-manager": ("shared.memory", "all", ["all", "memory"]),
    "news-generator": ("news.production", "news", ["news", "production"]),
    "news-polish": ("news.production", "news", ["news", "production"]),
    "novel-36-beats": ("novel.structure", "novel", ["novel", "structure"]),
    "novel-ai-wash": ("novel.polish", "novel", ["novel", "polish"]),
    "novel-batch-write": ("novel.batch-write", "novel", ["novel", "batch-write"]),
    "novel-checkpoint": ("novel.progress", "novel", ["novel", "progress"]),
    "novel-contexts": ("novel.context", "novel", ["novel", "context"]),
    "novel-dashboard": ("novel.dashboard", "novel", ["novel", "dashboard"]),
    "novel-debug": ("novel.baseline", "novel", ["novel", "baseline"]),
    "novel-evaluator": ("novel.review", "novel", ["novel", "review"]),
    "novel-foreshadowing-dag": ("novel.plot", "novel", ["novel", "plot"]),
    "novel-guardian": ("novel.guardian", "novel", ["novel", "guardian"]),
    "novel-guidelines": ("novel.baseline", "novel", ["novel", "baseline"]),
    "novel-init": ("novel.init", "novel", ["novel", "init"]),
    "novel-mcp-server": ("novel.integration", "novel", ["novel", "integration"]),
    "novel-mechanical-scorer": ("novel.quality", "novel", ["novel", "quality"]),
    "novel-metrics": ("novel.analytics", "novel", ["novel", "analytics"]),
    "novel-orchestrator": ("novel.orchestration", "novel", ["novel", "orchestration"]),
    "novel-quick-write": ("novel.quick-write", "novel", ["novel", "quick-write"]),
    "novel-receiving-review": ("novel.review", "novel", ["novel", "review"]),
    "novel-recovery": ("novel.recovery", "novel", ["novel", "recovery"]),
    "novel-safe-revision": ("novel.baseline", "novel", ["novel", "baseline"]),
    "novel-simplify": ("novel.baseline", "novel", ["novel", "baseline"]),
    "novel-voice-profile": ("novel.voice", "novel", ["novel", "voice"]),
    "novel-writer-cn": ("novel.creation", "novel", ["novel", "creation"]),
    "query-knowledge-graph": ("code.intelligence", "code", ["code", "intelligence"]),
    "query-symbol": ("code.intelligence", "code", ["code", "intelligence"]),
    "ralph": ("code.architecture", "code", ["code", "architecture"]),
    "receiving-code-review": ("code.review", "code", ["code", "review"]),
    "ripgrep-search": ("code.search", "code", ["code", "search"]),
    "security-bounty-hunter": ("code.security", "code", ["code", "security"]),
    "security-review": ("code.architecture", "code", ["code", "architecture"]),
    "systematic-debugging": ("code.testing", "code", ["code", "testing"]),
    "tdd-workflow": ("shared.docs", "shared", ["shared", "docs"]),
    "test-driven-development": ("shared.docs", "shared", ["shared", "docs"]),
    "two-stage-review": ("shared.workflow", "shared", ["review", "two-stage"]),
    "understand-project": ("code.intelligence", "code", ["code", "intelligence"]),
    "verification-loop": ("code.testing", "code", ["code", "testing"]),
    "web-design-guidelines": ("code.design", "code", ["code", "design"]),
    "web-tools-guide": ("shared.research", "shared", ["shared", "research"]),
}